import json
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from app.utils.config import settings


class EmbeddingServiceError(RuntimeError):
    """Raised when embeddings cannot be generated by the configured model endpoint."""


def embed_query(query: str) -> list[float]:
    """
    Convert a user query into a real model embedding vector.

    The service calls Ollama embedding endpoints and returns the first vector.
    """
    normalized_query = query.strip()
    if not normalized_query:
        raise EmbeddingServiceError("Cannot embed an empty query.")

    vectors = embed_texts([normalized_query])
    return vectors[0]


def embed_texts(texts: list[str]) -> list[list[float]]:
    """Embed a list of strings with the configured Ollama embedding model."""
    normalized_texts = [text.strip() for text in texts if text and text.strip()]
    if not normalized_texts:
        raise EmbeddingServiceError("No non-empty text was provided for embedding.")

    embed_url = f"{settings.ollama_base_url.rstrip('/')}/api/embed"
    payload = {
        "model": settings.ollama_embedding_model,
        "input": normalized_texts,
    }

    try:
        response_payload = _post_json(embed_url, payload)
        vectors = response_payload.get("embeddings")
        if not isinstance(vectors, list) or not vectors:
            raise EmbeddingServiceError("Embedding response did not include vectors.")

        parsed_vectors = [_coerce_vector(vector) for vector in vectors]
        if len(parsed_vectors) != len(normalized_texts):
            raise EmbeddingServiceError("Embedding response length did not match input length.")
        return parsed_vectors
    except EmbeddingServiceError:
        raise
    except Exception:
        # Backward compatibility for older Ollama versions that expose /api/embeddings.
        return [_embed_single_legacy(text) for text in normalized_texts]


def _embed_single_legacy(text: str) -> list[float]:
    legacy_url = f"{settings.ollama_base_url.rstrip('/')}/api/embeddings"
    payload = {
        "model": settings.ollama_embedding_model,
        "prompt": text,
    }
    response_payload = _post_json(legacy_url, payload)
    vector = response_payload.get("embedding")
    return _coerce_vector(vector)


def _coerce_vector(vector: object) -> list[float]:
    if not isinstance(vector, list) or not vector:
        raise EmbeddingServiceError("Received an invalid embedding vector.")

    try:
        coerced_vector = [float(value) for value in vector]
    except (TypeError, ValueError) as exc:
        raise EmbeddingServiceError(f"Embedding vector contains non-numeric values: {exc}") from exc

    if len(coerced_vector) != settings.embedding_dimension:
        raise EmbeddingServiceError(
            "Embedding dimension mismatch. "
            f"Expected {settings.embedding_dimension}, got {len(coerced_vector)}."
        )
    return coerced_vector


def _post_json(url: str, payload: dict[str, object]) -> dict[str, object]:
    request = Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    last_error: Exception | None = None
    for _ in range(max(1, settings.embedding_retries + 1)):
        try:
            with urlopen(request, timeout=settings.ollama_timeout_seconds) as response:
                parsed = json.loads(response.read().decode("utf-8"))
            break
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as exc:
            last_error = exc
    else:
        raise EmbeddingServiceError(
            "Failed to generate embeddings from Ollama "
            f"({settings.ollama_base_url}, model={settings.ollama_embedding_model}): {last_error}"
        ) from last_error

    if not isinstance(parsed, dict):
        raise EmbeddingServiceError("Embedding endpoint returned a non-object payload.")
    return parsed
